services:
  health-worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    ports:
      - "50051:50051"
    networks:
      - healthchecker-net
    depends_on:
      - redis

  api-gateway:
    build:
      context: ..
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    networks:
      - healthchecker-net
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
    networks:
      - healthchecker-net

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9093:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - healthchecker-net
    depends_on:
      - api-gateway
      - health-worker
      - cadvisor

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - healthchecker-net
    depends_on:
      - prometheus

  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"
    networks:
      - healthchecker-net

networks:
  healthchecker-net:
    driver: bridge
volumes:
  grafana-data: {}