services:
  health-worker:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    ports:
      - "50051:50051"
    networks:
      - healthchecker-net

  api-gateway:
    build:
      context: ..
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    networks:
      - healthchecker-net

networks:
  healthchecker-net:
    driver: bridge
