FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/api-gateway ./cmd/api-gateway

FROM alpine:latest
COPY --from=builder /app/api-gateway /api-gateway
EXPOSE 8080 9090
CMD ["/api-gateway"]